version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
      
  node_api:
    build: .
    ports:
      - 3002:3002
    environment:
      PORT: 3002
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}